# Use with Kubernetes 1.7+
################################
# Istio initializer
################################
apiVersion: v1
kind: ConfigMap
metadata:
  name: istio-inject-dc
  namespace: istio-system
data:
  config: |-
    policy: "enabled"
    namespaces: [""] # everything, aka v1.NamespaceAll, aka cluster-wide
    initializerName: "sidecar-dc.initializer.istio.io"
    params:
      initImage: docker.io/istio/proxy_init:0.4.0
      proxyImage: docker.io/istio/proxy:0.4.0
      verbosity: 2
      version: 0.4.0
      meshConfigMapName: istio-dc
      imagePullPolicy: IfNotPresent
      debugMode: true
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: istio-initializer-service-account
  namespace: istio-system
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: istio-openshift-initializer
  namespace: istio-system
  annotations:
    sidecar.istio.io/inject: "false"
  initializers:
    pending: []
  labels:
    istio: istio-initializer-dc
spec:
  replicas: 1
  template:
    metadata:
      name: istio-initializer-dc
      labels:
        istio: initializer-dc
      annotations:
        sidecar.istio.io/inject: "false"
    spec:
      serviceAccountName: istio-initializer-service-account
      containers:
        - name: initializer
          image: docker.io/karmab/istio-openshift-initializer:latest
          imagePullPolicy: IfNotPresent
          args:
            - --port=8083
            - --namespace=istio-system
            - -v=2
          volumeMounts:
          - name: config-volume
            mountPath: /etc/istio/config
      volumes:
      - name: config-volume
        configMap:
          name: istio
---
apiVersion: admissionregistration.k8s.io/v1alpha1
kind: InitializerConfiguration
metadata:
  name: istio-sidecar-dc
initializers:
  - name: sidecar-dc.initializer.istio.io
    rules:
      - apiGroups:
          - "*"
        apiVersions:
          - "*"
        resources:
          - deploymentconfigs
---
